kumuluzee:
  name: projektPolnilne
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PolnilnePostajeDS
      connection-url: jdbc:postgresql://localhost:5432/projektPostaje
      username: postgres
      password: postgres