kumuluzee:
  name: projektPolnilne
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PolnilnePostajeDS
      connection-url: jdbc:postgresql://host.docker.internal:5432/postajeDB
      username: postgres
      password: postgres
  health:
    checks:
      data-source-health-check:
        - jndi-name: jdbc/PolnilnePostajeDS
          type: liveness
      disk-space-health-check:
        threshold: 1000
  dev:
    scan-libraries:
      - storitve
  openapi-mp:
    enabled: true
  security:
    keycloak:
      json: '{"realm": "users-realm",
            "bearer-only": true,
            "auth-server-url": "http://localhost:8082/auth/",
            "ssl-required": "external",
            "resource": "users-api",
            "confidential-port": 0}'
integrations:
  upravljanjeRezervacij:
    base-url: http://localhost:8081/v1